---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-app
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: "devopshint/node-app:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
spec:
  selector:
    app: node-app
  type: ClusterIP
  ports:
  - name: http
    targetPort: 3000
    port: 80