---
name: Deploy to Minikube using GitHub Actions

on:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          name: Try the cluster !

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo "Verifying images:"
          docker images         

      - name: Deploy to minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
      - name: Get pod logs
        run: kubectl logs -l app=nodejs-app