---
name: Deploy to Minikube using GitHub Actions
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: |
          kubectl get pods -A
          kubectl get svc -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          echo "${{ secrets.DOCKER_ACCESS }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password "${{ secrets.DOCKER_HUB_PASS }}"
          docker build -f ./Dockerfile -t hhkp/node-app:latest .
          docker push hhkp/node-app:latest
          echo -n "verifying images:"
          docker images
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to minikube
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl get pods -A
          kubectl get svc -A
          kubectl get deployment -A
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
          curl $(minikube service nodejs-app --url)/version